name: Build And Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: | 
       git config --global user.name "$GITHUB_ACTOR"
       git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
       npm install
       npm run build
       cd dist
       git init
       git add -A
       git commit -m 'deploy'
       git push -f https://${GITHUB_ACTOR}:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
       cd -
