name: Build And Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: prodismydev
          password: ${{ secrets.TOKEN }}
          repository: covidioten/ui/ui
          registry: docker.pkg.github.com
          tags: latest
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker stop covidioten-ui
            docker rm covidioten-ui
            docker pull docker.pkg.github.com/covidioten/ui/ui:latest
            docker run -p 8101:8080 -d --network=covidioten_network --name covidioten-ui docker.pkg.github.com/covidioten/ui/ui:latest
